export const mycourses = [	
	{
		"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "1",
		"route": "https://eventos.upm.es/130197/detail/introduccion-a-la-inteligencia-artificial-generativa-a-traves-de-los-grandes-modelos-de-lenguaje.html",
		"title": "Introducción a la inteligencia artificial generativa a través de los grandes modelos de lenguaje",
		"description": "Curso para obtener una base técnica sólida en IA generativa, entender y adaptar Grandes Modelos de Lenguaje (LLMs), y aplicarlos de forma segura.",
	    "gradient": "bg-yellow-gradient",
	},
	{
		"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "3",
		"route": "https://eventos.upm.es/124256/detail/itinerario-desarrollo-web-fullstack.html",
		"title": "Itinerario: Desarrollo Web Fullstack",
		"description": "Este itinerario ha sido diseñado como una serie 5 MOOC para cubrir las competencias necesarias para el desarrollo de aplicaciones fullstack. Incluyendo desarrollo de aplicaciones web de cliente con HTML/JS/CSS y con React, desarrollo del servidor con node.js, bases de datos (relacionales y no relacionales) y aplicaciones móviles Android e iOS con React Native.",
	    "gradient": "bg-purple-gradient",
	},
	{	"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "2",
		"route": "https://eventos.upm.es/124560/detail/bases-de-datos-relacionales-y-no-relacionales-conceptos-diseno-y-aplicacion-a-entornos-web-edicion-.html",
		"title": "Bases de Datos Relacionales y No Relacionales: conceptos, diseño y aplicación a entornos web",
		"description": "Los objetivos principales incluyen conocer y controlar los conceptos fundamentales de modelos de datos y de su diseño, los lenguajes de bajo y alto nivel necesarios para administrar bases de datos y la conexión de aplicaciones web a dichas bases de datos. Todo ello con enfoque comparativo entre las bases de datos relacionales y las no relacionales. Se estudiarán tecnologías y lenguajes como SQL, NoSQL, MySQL o MongoDB.",
        "gradient": "bg-blue-gradient",
    },
    {
		"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "3",
		"route": "https://eventos.upm.es/125497/detail/desarrollo-de-aplicaciones-con-react-y-react-native-edicion-3.html",
		"title": "Desarrollo de aplicaciones con React y React Native",
		"description": "El objetivo principal del curso es aprender sobre las tecnologías de React y React Native. Estas son una manera novedosa y muy potente de desarrollar aplicaciones de cliente, tanto aplicaciones web como aplicaciones nativas Android e iOS. Son una de las tecnologías más demandadas en el mercado laboral hoy en día, y este curso te permitirá dominarlas y hacer tus propias aplicaciones de forma autónoma.",
        "gradient": "bg-purple-gradient",
    },    
    {
		"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "7",
		"route": "https://eventos.upm.es/125057/detail/desarrollo-backend-con-node-js-express-y-bbdds-edicion-7.html",
		"title": "Desarrollo Backend con Node.js, Express y BBDDs",
		"description": "Este curso capacita para un nivel intermedio de desarrollo de aplicaciones Web de servidor utilizando las HTML5, CSS3, JavaScript, node.js y express.js. El curso repasa y utiliza también conceptos básicos de ingeniería software, tales como estructura de proyectos, empaquetado de aplicaciones, gestión de versiones. ",
		"gradient": "bg-yellow-gradient",
	},
	{
		"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "15",
		"route": "https://eventos.upm.es/125307/detail/desarrollo-frontend-con-html-css-y-javascript-edicion-15.html",
		"title": "Desarrollo Frontend con HTML, CSS y JavaScript",
		"description": "Este curso capacita para un nivel intermedio de desarrollo de aplicaciones Web de cliente utilizando HTML5, CSS3, JavaScript.",
		"gradient": "bg-yellow-gradient",
	},
	{
		"date": "2025",
		"logo": "/assets/img/courses/fondo-cursos-png",
		"edition": "8",
		"route": "https://eventos.upm.es/125178/detail/gestion-de-proyectos-software-con-git-y-github-edicion-8.html",
		"title": "Gestión de proyectos software con Git y GitHub",
		"description": "Este MOOC capacita en el uso de las herramientas Git y GitHub para el control y la gestión de proyectos software, individualmente o en equipos de personas, que utilizan la herramienta Git para compartir repositorios en el portal GitHub (https://github.com). ",
		"gradient": "bg-blue-gradient",
	},
    {
		"date": "2021",
		"logo": "/assets/img/courses/fondo-cursos.png",
		"edition": "5",
		"route": "https://eventos.upm.es/60707/detail/siete-habilidades-clave-en-la-era-digital.html",
		"title": "Siete habilidades clave en la era digital",
		"description": "Las profesiones del mañana serán nuevas y no se conocen aún. Por ello es importante formarse en ciertas habilidades transversales que, independientemente del tipo del tipo de profesión que se desarrolle ahora o se vaya a desarrollar en el futuro, son esenciales para aprovechar las oportunidades del mundo digital. Son las siguientes: 1. Comunicación y Storytelling - Ángel González 2. Creatividad - Fabián García Pastor 3. Emprendimiento - Luis Miguel Olivas 4. Empatía digital - Alfredo Corell 5. STEM - Juan Medina 6. Gestión de la información y Pensamiento crítico - David Carabantes 7. Programación - Juan Quemada ",
		"gradient": "bg-purple-gradient",
	},
    {
		"date": "2018",
		"logo": "/assets/img/courses/fondo-cursos-png",
		"edition": "2",
		"route": "https://innovacioneducativa.upm.es/mooc/informacion-mooc?idmooc=2117",
		"title": "Introducción a LINUX como entorno de desarrollo de sistemas software",
		"description": "El objetivo del curso es proporcionar a los estudiantes los conocimiento teóricos y prácticos necesarios para empezar a utilizar el sistema operativo LINUX como entorno de soporte para el desarrollo de aplicaciones del software. ",
		"gradient": "bg-purple-gradient",

	},
];
